#include <stdio.h>

int main() {
    puts(
        "\n===== NETLAB SHELL HELP =====\n"
        "Copyright @ R. Aisha Syauqi Ramadhani - 2306250554\n"
        "-Use the shell at your own risk...\n"
        "\nList of Commands supported:\n"
        "> print {something}                      : Print something with style\n"
        "    -h, --help                           : Show print command help\n"
        "    -u                                   : Convert text to UPPERCASE\n"
        "    -l                                   : Convert text to lowercase\n"
        "    -r                                   : Print text in reverse\n"
        "> buatdong {filename} {content}          : Write content to a file\n"
        "    -h, --help                           : Show buatdong command help\n"
        "> bacadong {filename}                    : Read from a file\n"
        "    -h, --help                           : Show bacadong command help\n"
        "> rahasiabanget {filename} {content}     : Write to a file (encrypted)\n"
        "    -h, --help                           : Show rahasiabanget command help\n"
        "> pembacapikiran {filename}              : Read from a file (encrypted)\n"
        "    -h, --help                           : Show pembacapikiran command help\n"
        "> itungwoi {add|sub|mul|div} num1 num2   : Do some calculation\n"
        "    -h, --help                           : Show itungwoi command help\n"
        "> help                                   : Show all commands in shell\n"
        "> exit                                   : Exit the shell\n"
        "> clear                                  : Clear the terminal screen\n"
        "> waktusekarang                          : Show current date and time\n"
        "> hitungram {filename}                   : Count lines, words, and characters in a file\n"
        "> list                                   : List the contents of the current directory\n"
        "> rename {oldname} {newname}             : Rename a file or directory\n"
        "> hapusfile {filename}                   : Delete a file\n"
        "> caridong {pattern} [directory]         : Searches for files containing a specific pattern\n"
        "    -i                                   : Case insensitive search\n"
        "    -r                                   : Recursive search in subdirectories\n"
        "    -n                                   : Show line numbers with matches\n"
        "    -c                                   : Count matches only\n"
        "> sortirdong {filename} [column]         : Sort file contents\n"
        "    -n                                   : Sort numerically\n"
        "    -r                                   : Sort in reverse order\n"
        "    -u                                   : Remove duplicates\n"
        "    -f                                   : Case insensitive sorting\n"
        "> proseswoi                              : List or manage running processes\n"
        "    -a                                   : Show all processes\n"
        "    -k {pid}                             : Kill process by PID\n"
        "    -m                                   : Sort by memory usage\n"
        "    -c                                   : Sort by CPU usage\n"
        "> netwoi [interface]                     : Display network information\n"
        "    -a                                   : Show all interfaces\n"
        "    -i                                   : Show IP addresses only\n"
        "    -s                                   : Show connection statistics\n"
        "    -m                                   : Show MAC addresses\n"
        "> statsdong {filename}                   : Perform statistical analysis on data file\n"
        "    -a                                   : Calculate mean, median, mode\n"
        "    -g                                   : Generate graph of data distribution\n"
        "    -c {column}                          : Select column for analysis\n"
        "    -n                                   : Normalize data (0-1 range)\n"
        "\nSpecial Features:\n"
        "> Pipe (|)                               : Connect the output of first command as input to second command\n"
        "    Example: itungwoi add 5 3 | print    : Will print the result of addition (8.00)\n"
        "    Example: list | print                : Will print the contents of the directory\n"
        "    Example: caridong \"text\" | sortirdong -u : Find text and display unique results\n"
        "    Example: bacadong file.txt | statsdong -a : Read file and calculate statistics\n"
        "    Example: netwoi -i | print -u        : Display IP addresses in uppercase\n"
        "\nGeneral Usage Tips:\n"
        "> Type \"{Command} -h\" to see the help for a specific command\n"
        "> All commands support the -h or --help flag for displaying command-specific help\n"
        "> Use pipe (|) to redirect output from one command to another\n"
        "> Multiple flags can be combined (e.g., 'caridong -ir pattern')\n"
    );
    return 0;
}